# Generated by Django 4.2.4 on 2024-01-02 06:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="jobModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100, null=True)),
                ("company_name", models.CharField(max_length=100, null=True)),
                ("location", models.CharField(max_length=100, null=True)),
                ("description", models.TextField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
