# Generated by Django 4.2.9 on 2024-01-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_jobmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobmodel",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
