# Generated by Django 4.2.9 on 2024-01-08 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0004_recruiterprofile_jobseekerprofile"),
    ]

    operations = [
        migrations.RemoveField(model_name="jobseekerprofile", name="profile_picture",),
        migrations.RemoveField(model_name="recruiterprofile", name="profile_picture",),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.ImageField(null=True, upload_to="media/profile_pic"),
        ),
        migrations.AlterField(
            model_name="jobseekerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobseekerProfile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="recruiterprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recruiterProfile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
